version: '2'
services:
  scraper:
    build: .
    restart: on-failure
    volumes:
      - "./scraper.log:/app/cnb_unitn.log"
    depends_on:
      - db
  db:
    image: rethinkdb
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:28015:28015"
